### ISSUE TITLE
Broken Skin on Dedicated Server

### ISSUE THREAD

**Issue by facetorched** [Parker8283/LanHostSkinRefixed#1]
Joining a dedicated server while the mod is installed on the client causes my skin to be steve. Singleplayer it is fine.
@Parker8283 (pinging because I'm not sure if it otherwise sends a notification)

**Comment by Parker8283** [comment]
I own the repo, so I get the notification. At isn't required.

Can you describe more? Do you see your own skin as Steve when joining a dedicated server? Do others see your skin as Steve?

I'll try to find time soon to test this myself, but some generic things you can try if you haven't already:
* If you had other mods installed, remove all but this one and try again.
* Try a single-player LAN world and have others join if possible, see if that has the same issue.

**Comment by facetorched** [comment]
Ah sorry. In the past i haven't gotten responses without the ping. Must be notification settings.

It is just me looking at myself when joining a server (pressing f5). And yes, I have tried with only this mod installed and the issue persists.

I'm not sure how to test what other players see without someone willing to help me test. Opening to LAN of course does nothing for what I personally see but I assume people in the comments aren't lying and this mod fixes what it intends to -- and so it works with LAN.

**Comment by Parker8283** [comment]
Turns out to have been a bad interaction with another patch I had included when I rewrote this mod. It worked if you started a single-player first then joined a server, because I was only having the game request the skin from the skin server for single-player worlds now. Now it's requesting it for both single-player and server.

rv1 should be live on CurseForge soon.
